const modules=[
{id:1,title:'Mentalidade de Alta Performance',desc:'Postura, energia, disciplina e padrão de execução de um captador forte.',xp:300,lessons:[['1.1','O papel do captador','Você não entrega apenas um convite: você cria a primeira impressão da experiência. Postura aberta, energia controlada e comunicação clara aumentam a confiança.'],['1.2','Regra dos 3 segundos','Ao identificar um casal dentro do perfil, decida e inicie a abordagem rapidamente. Pensar demais reduz presença e naturalidade.'],['1.3','Meta de processo','Controle o que depende de você: volume de abordagens, qualidade da conversa e consistência. Resultado vem como consequência do processo.']],quiz:{q:'Qual é a prioridade de um captador de alta performance?',o:['Esperar apenas clientes que demonstrem interesse','Controlar volume, qualidade e consistência das abordagens','Falar o máximo possível sem ouvir o cliente'],a:1}},
{id:2,title:'Abordagem que Para o Cliente',desc:'Como abrir conversa com naturalidade e ganhar atenção sem pressionar.',xp:400,lessons:[['2.1','Presença antes da fala','Contato visual, sorriso leve, distância adequada e corpo voltado ao casal. A abordagem começa antes da primeira palavra.'],['2.2','Abertura curta','Use uma frase simples, humana e objetiva. Evite despejar informação. Primeiro conquiste atenção, depois explique.'],['2.3','Microcompromisso','Faça uma pergunta fácil que mantenha a conversa: “Vocês estão passeando por aqui hoje?” ou “É a primeira vez de vocês na cidade?”']],quiz:{q:'Uma boa abertura deve ser:',o:['Longa e completa para evitar dúvidas','Curta, natural e seguida de uma pergunta simples','Agressiva para impedir o cliente de sair'],a:1}},
{id:3,title:'Qualificação Inteligente',desc:'Descubra rapidamente se o casal tem perfil sem transformar a conversa em interrogatório.',xp:450,lessons:[['3.1','Conversa, não formulário','Alterne pergunta e contexto. Uma pergunta por vez e sempre com tom de conversa.'],['3.2','Sinais de perfil','Observe disponibilidade, composição do casal, interesse, momento da viagem e critérios internos da operação.'],['3.3','Transição elegante','Ao confirmar perfil, conecte o benefício ao próximo passo. Evite mudança brusca de assunto.']],quiz:{q:'Qual a melhor forma de qualificar?',o:['Fazer todas as perguntas de uma vez','Conversar e validar critérios aos poucos','Evitar perguntas para não perder o cliente'],a:1}},
{id:4,title:'Objeções sem Confronto',desc:'Aprenda a contornar “sem tempo”, “não quero” e “depois eu vejo” com leveza.',xp:500,lessons:[['4.1','Não rebata','Objeção não é briga. Valide primeiro: “Entendo perfeitamente”. Depois esclareça o ponto principal.'],['4.2','Sem tempo','Reduza incerteza com objetividade. Explique duração, benefício e próximo passo sem inventar promessa.'],['4.3','Não tenho interesse','Descubra o motivo real com uma pergunta curta. Se a pessoa realmente não quiser, encerre com respeito.']],quiz:{q:'Ao receber uma objeção, o primeiro passo é:',o:['Contradizer imediatamente','Validar e entender antes de responder','Aumentar o tom de voz'],a:1}},
{id:5,title:'Encaminhamento e Fechamento',desc:'Transforme uma boa conversa em ação clara, sem deixar o cliente esfriar.',xp:550,lessons:[['5.1','Próximo passo claro','Quando houver aceite, conduza. Evite terminar com “se quiser”. Diga exatamente o que acontece agora.'],['5.2','Recapitule o valor','Antes de encaminhar, reforce em uma frase o benefício e o combinado.'],['5.3','Passagem de bastão','Transmita segurança na transição para o próximo profissional e não gere informação conflitante.']],quiz:{q:'Depois do aceite do casal, você deve:',o:['Abrir várias novas possibilidades','Conduzir para o próximo passo com clareza','Voltar ao início da apresentação'],a:1}},
{id:6,title:'Campo: Ritmo, Ponto e Consistência',desc:'Como manter performance durante o dia e recuperar rapidamente após negativas.',xp:600,lessons:[['6.1','Ritmo de campo','Trabalhe em blocos. Após uma negativa, reposicione-se e volte para a próxima oportunidade sem carregar a conversa anterior.'],['6.2','Leitura do ponto','Observe fluxo, direção das pessoas, horários e zonas de melhor abordagem. Posicionamento reduz esforço desperdiçado.'],['6.3','Fechamento do dia','Revise números, objeções repetidas e o que funcionou. Escolha um ajuste específico para o próximo turno.']],quiz:{q:'Depois de uma sequência de negativas, o melhor é:',o:['Parar de abordar por um longo período','Recuperar postura e voltar ao processo rapidamente','Mudar totalmente o discurso a cada cliente'],a:1}}
];

const scenarios=[
{q:'O casal responde: “Estamos com pressa, só estamos passeando.”',answers:[['Tudo bem. Em 20 segundos eu explico e vocês decidem se faz sentido.',true],['Então vocês não têm interesse nenhum?',false],['Mas vocês precisam parar para me ouvir.',false]],tip:'Valide a pressa e peça um microespaço de tempo. O objetivo é reduzir resistência, não confrontar.'},
{q:'A pessoa diz: “Não quero comprar nada.”',answers:[['Perfeito, e eu não preciso que vocês comprem nada agora. Posso só explicar a experiência?',true],['Mas eu nem falei o preço ainda!',false],['Se não quer comprar, deixa pra lá.',false]],tip:'Não entre em disputa. Esclareça a intenção da abordagem e mantenha leveza.'},
{q:'O casal continua andando enquanto você fala.',answers:[['Acompanhar mantendo distância adequada e fazer uma pergunta curta.',true],['Segurar a pessoa pelo braço.',false],['Começar a falar mais rápido e mais alto.',false]],tip:'Respeite o espaço físico. Uma pergunta curta pode recuperar atenção; contato físico não deve ser usado.'},
{q:'O cliente pergunta algo que você não sabe responder com certeza.',answers:[['Dizer que vai confirmar a informação com o responsável.',true],['Inventar uma resposta para não perder o casal.',false],['Mudar de assunto sem responder.',false]],tip:'Confiança também vem de transparência. Nunca prometa ou informe algo que você não pode confirmar.'}
];

const storeKey='captaAcademyStateV1';
const defaultState={name:'',xp:0,completed:[],quizScores:{},lastVisit:'',streak:1,simHits:0,simTotal:0};
let state={...defaultState,...JSON.parse(localStorage.getItem(storeKey)||'{}')};
let deferredPrompt=null;
const app=document.querySelector('#app');
const quizDialog=document.querySelector('#quizDialog');
const quizContent=document.querySelector('#quizContent');

function save(){localStorage.setItem(storeKey,JSON.stringify(state));}
function initials(name=state.name||'RB'){return name.trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'RB';}
function visit(){const today=new Date().toISOString().slice(0,10);if(!state.lastVisit){state.lastVisit=today;}else if(state.lastVisit!==today){const prev=new Date(state.lastVisit);const now=new Date(today);const diff=Math.round((now-prev)/86400000);state.streak=diff===1?(state.streak||1)+1:1;state.lastVisit=today;}save();}
function completedCount(){return state.completed.length;}
function totalLessons(){return modules.reduce((n,m)=>n+m.lessons.length,0);}
function progress(){return Math.round(completedCount()/totalLessons()*100);}
function setNav(route){document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===route));document.querySelector('#profileBtn').textContent=initials();}
function moduleProgress(m){return Math.round(m.lessons.filter(l=>state.completed.includes(`${m.id}-${l[0]}`)).length/m.lessons.length*100);}
function isUnlocked(m){return m.id===1||moduleProgress(modules[m.id-2])===100;}
function awardLesson(mid,lid){const key=`${mid}-${lid}`;if(!state.completed.includes(key)){state.completed.push(key);state.xp+=75;save();}}
function cardModule(m){const p=moduleProgress(m),open=isUnlocked(m);return `<article class="card module-card ${open?'':'locked'}"><div><div class="module-num">MÓDULO ${String(m.id).padStart(2,'0')} ${open?'':'• BLOQUEADO'}</div><h3>${m.title}</h3><p>${m.desc}</p></div><div><div class="module-meta"><span class="pill">${m.lessons.length} aulas</span><span class="pill">+${m.xp} XP</span><span class="pill">${p}% concluído</span></div><div class="progress-track" style="margin:12px 0"><div class="progress-bar" style="width:${p}%"></div></div>${open?`<button class="secondary-btn" onclick="location.hash='modulo-${m.id}'">${p?'Continuar':'Começar'}</button>`:'<button class="secondary-btn" disabled>Conclua o módulo anterior</button>'}</div></article>`;}

function home(){setNav('home');const next=modules.find(m=>isUnlocked(m)&&moduleProgress(m)<100)||modules.at(-1);app.innerHTML=`<section class="hero"><div class="eyebrow">Treinamento de campo</div><h1>${state.name?`Vamos evoluir, ${state.name.split(' ')[0]}.`:'Domine a arte da captação.'}</h1><p>Treinamento direto ao ponto para melhorar abordagem, qualificação, objeções e conversão. Aprenda, simule e leve para o campo.</p><div class="hero-actions"><button class="primary-btn" onclick="location.hash='modulo-${next.id}'">Continuar treinamento</button><button class="secondary-btn" onclick="location.hash='simulador'">Treinar abordagem</button></div></section><section class="stats"><div class="stat-card"><small>Seu progresso</small><strong>${progress()}%</strong></div><div class="stat-card"><small>XP acumulado</small><strong>${state.xp.toLocaleString('pt-BR')}</strong></div><div class="stat-card"><small>Aulas concluídas</small><strong>${completedCount()}/${totalLessons()}</strong></div><div class="stat-card"><small>Sequência</small><strong>${state.streak||1} dia${state.streak===1?'':'s'}</strong></div></section><div class="section-head"><div><h2>Próximas trilhas</h2><p>Avance em ordem e consolide a base.</p></div><a href="#trilhas">Ver todas</a></div><section class="grid">${modules.slice(0,3).map(cardModule).join('')}</section><div class="section-head"><div><h2>Desafio rápido</h2><p>Um minuto de prática antes de entrar em campo.</p></div></div><section class="card sim-card"><div class="eyebrow">DESAFIO DO DIA</div><p class="scenario">Um casal passou por você e disse “agora não”. Qual seria sua próxima frase sem pressionar?</p><button class="primary-btn" onclick="location.hash='simulador'">Responder no simulador</button></section>`;}

function trilhas(){setNav('trilhas');app.innerHTML=`<section class="hero"><div class="eyebrow">Jornada completa</div><h1>Da primeira abordagem ao encaminhamento.</h1><p>Seis módulos em sequência. Cada etapa desbloqueia a próxima para garantir domínio da base.</p></section><div class="section-head"><div><h2>Trilha de Captação</h2><p>${completedCount()} de ${totalLessons()} aulas concluídas.</p></div></div><section class="grid">${modules.map(cardModule).join('')}</section>`;}

function moduleView(id){const m=modules.find(x=>x.id===id);if(!m){location.hash='trilhas';return;}setNav('trilhas');if(!isUnlocked(m)){app.innerHTML='<div class="empty">Conclua o módulo anterior para desbloquear esta etapa.</div>';return;}const p=moduleProgress(m);app.innerHTML=`<section class="hero"><div class="eyebrow">MÓDULO ${String(m.id).padStart(2,'0')}</div><h1>${m.title}</h1><p>${m.desc}</p><div class="module-meta"><span class="pill">${p}% concluído</span><span class="pill">${m.lessons.length} aulas</span><span class="pill">Quiz final</span></div></section><div class="section-head"><div><h2>Aulas</h2><p>Leia, pratique e marque como concluída.</p></div></div><section class="lesson-list">${m.lessons.map(l=>{const key=`${m.id}-${l[0]}`,done=state.completed.includes(key);return `<article class="card lesson"><div class="lesson-icon">${done?'✓':'▶'}</div><div><strong>${l[1]}</strong><p>${l[2]}</p></div><button class="${done?'ghost-btn':'secondary-btn'}" onclick="completeLesson(${m.id},'${l[0]}')">${done?'Concluída':'Concluir'}</button></article>`}).join('')}</section><div class="section-head"><div><h2>Validação do módulo</h2><p>Teste o que você aprendeu.</p></div></div><section class="card"><div class="lesson"><div class="lesson-icon">?</div><div><strong>Quiz rápido</strong><p>Acertando, você recebe +${m.xp} XP.</p></div><button class="primary-btn" onclick="openQuiz(${m.id})" ${p<100?'disabled title="Conclua as aulas primeiro"':''}>${state.quizScores[m.id]?'Refazer quiz':'Iniciar quiz'}</button></div></section>`;}
window.completeLesson=(mid,lid)=>{awardLesson(mid,lid);moduleView(mid);};

window.openQuiz=(mid)=>{const m=modules.find(x=>x.id===mid);quizContent.innerHTML=`<div class="quiz-status">QUIZ • MÓDULO ${mid}</div><h2>${m.quiz.q}</h2>${m.quiz.o.map((o,i)=>`<button class="answer-btn quiz-option" onclick="answerQuiz(${mid},${i})">${String.fromCharCode(65+i)}. ${o}</button>`).join('')}<button class="ghost-btn" onclick="quizDialog.close()">Fechar</button>`;quizDialog.showModal();};
window.answerQuiz=(mid,i)=>{const m=modules.find(x=>x.id===mid),ok=i===m.quiz.a,first=!state.quizScores[mid];if(ok){state.quizScores[mid]=100;if(first)state.xp+=m.xp;save();quizContent.innerHTML=`<div class="brand-mark big">✓</div><h2>Resposta certa!</h2><p>Você concluiu a validação deste módulo${first?` e ganhou <strong>+${m.xp} XP</strong>`:''}.</p><button class="primary-btn" onclick="quizDialog.close();location.hash='trilhas'">Continuar jornada</button>`;}else{quizContent.innerHTML=`<div class="quiz-status">TENTE NOVAMENTE</div><h2>Quase.</h2><p>Revise o conceito e escolha a alternativa que prioriza uma abordagem profissional, simples e respeitosa.</p><button class="primary-btn" onclick="openQuiz(${mid})">Tentar de novo</button>`;}};

function simulador(){setNav('simulador');const s=scenarios[Math.floor(Math.random()*scenarios.length)];app.innerHTML=`<section class="hero"><div class="eyebrow">SIMULADOR DE CAMPO</div><h1>Treine antes de abordar.</h1><p>Escolha a resposta que você usaria na situação real e receba feedback instantâneo.</p></section><div class="section-head"><div><h2>Cenário</h2><p>Responda como se estivesse no ponto de captação.</p></div></div><section class="card sim-card" id="scenarioBox"><div class="eyebrow">CLIENTE</div><p class="scenario">“${s.q}”</p><div class="answer-grid">${s.answers.map((a,i)=>`<button class="answer-btn" onclick='answerScenario(${JSON.stringify({ok:a[1],tip:s.tip}).replaceAll("'","&#39;")},this)'>${a[0]}</button>`).join('')}</div></section>`;}
window.answerScenario=(data,btn)=>{state.simTotal++;if(data.ok){state.simHits++;state.xp+=25;}save();document.querySelectorAll('.answer-btn').forEach(b=>b.disabled=true);btn.style.borderColor=data.ok?'#22c55e':'#fb7185';document.querySelector('#scenarioBox').insertAdjacentHTML('beforeend',`<div class="feedback"><strong>${data.ok?'Boa resposta.':'Pode melhorar.'}</strong><br>${data.tip}<div style="margin-top:12px"><button class="secondary-btn" onclick="simulador()">Próximo cenário</button></div></div>`);};

function ranking(){setNav('ranking');const hit=state.simTotal?Math.round(state.simHits/state.simTotal*100):0;const rows=[['🥇','Camila','5.480'],['🥈','André','4.925'],['🥉','Felipe','4.360'],['4','Jessica','3.980'],['•',state.name||'Você',state.xp.toLocaleString('pt-BR')]];app.innerHTML=`<section class="hero"><div class="eyebrow">PERFORMANCE</div><h1>Treino também é competição.</h1><p>O ranking abaixo está pronto para receber dados reais quando o app for conectado à base da equipe.</p></section><section class="stats"><div class="stat-card"><small>Seu XP</small><strong>${state.xp.toLocaleString('pt-BR')}</strong></div><div class="stat-card"><small>Acerto em simulações</small><strong>${hit}%</strong></div><div class="stat-card"><small>Módulos validados</small><strong>${Object.keys(state.quizScores).length}/6</strong></div><div class="stat-card"><small>Sequência</small><strong>${state.streak||1}</strong></div></section><section class="card"><div class="section-head" style="margin-top:0"><div><h2>Ranking de treinamento</h2><p>Prévia demonstrativa da estrutura de competição.</p></div></div>${rows.map(r=>`<div class="rank-row"><div class="rank-pos">${r[0]}</div><div class="rank-avatar">${initials(r[1])}</div><div><strong>${r[1]}</strong><div style="color:var(--muted);font-size:12px">Captação</div></div><div class="rank-xp">${r[2]} XP</div></div>`).join('')}</section>`;}

function perfil(){setNav('perfil');const hit=state.simTotal?Math.round(state.simHits/state.simTotal*100):0;app.innerHTML=`<section class="profile-grid"><article class="card profile-hero"><div class="avatar-large">${initials()}</div><h2>${state.name||'Captador'}</h2><p style="color:var(--muted)">Em desenvolvimento</p><div class="score-ring" style="--p:${progress()}"><span>${progress()}%</span></div><p style="color:var(--muted);margin-top:12px">Progresso total</p><button class="secondary-btn" onclick="editName()">Editar nome</button></article><article class="card"><div class="eyebrow">SEU DESEMPENHO</div><h2 style="margin-top:8px">Resumo de evolução</h2><div class="stats" style="margin-bottom:20px"><div class="stat-card"><small>XP</small><strong>${state.xp}</strong></div><div class="stat-card"><small>Simulações</small><strong>${state.simTotal}</strong></div><div class="stat-card"><small>Acerto</small><strong>${hit}%</strong></div><div class="stat-card"><small>Aulas</small><strong>${completedCount()}</strong></div></div><h3>Conquistas</h3><div class="badges"><span class="badge">⚡ Primeiro passo</span>${completedCount()>=3?'<span class="badge">🎯 Base construída</span>':''}${Object.keys(state.quizScores).length>=3?'<span class="badge">🧠 Conhecimento validado</span>':''}${state.simHits>=5?'<span class="badge">🏆 Mestre da simulação</span>':''}</div></article></section>`;}
window.editName=()=>{document.querySelector('#nameInput').value=state.name;document.querySelector('#nameDialog').showModal();};

function route(){const h=(location.hash||'#home').slice(1);if(h.startsWith('modulo-'))return moduleView(Number(h.split('-')[1]));({home,trilhas,simulador,ranking,perfil}[h]||home)();window.scrollTo({top:0,behavior:'smooth'});}
window.addEventListener('hashchange',route);
document.querySelector('#profileBtn').addEventListener('click',()=>location.hash='perfil');
document.querySelector('#nameForm').addEventListener('submit',e=>{const v=document.querySelector('#nameInput').value.trim();if(v){state.name=v;save();setTimeout(route,0);}});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;document.querySelector('#installBtn').hidden=false;});
document.querySelector('#installBtn').addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;document.querySelector('#installBtn').hidden=true;});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
visit();route();if(!state.name)setTimeout(()=>document.querySelector('#nameDialog').showModal(),250);
